---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3
inputs:
  - name: concourse
  - name: src
outputs:
  - name: src-artifacts
run:
  path: concourse/tasks/pylama/run.sh
