steps:
  - label: ":python: Format"
    command: |
      echo "--- Installing dependencies"
      pipenv install --deploy --dev
      echo "+++ Running formatter"
      /usr/local/bin/black --check bin/buildkite
